### ISSUE TITLE
Error when using bardapi asynchronously

### ISSUE THREAD

**Issue by akos326** [dsdanielpark/Bard-API#140]
**Describe the bug**
I'm trying to use BardAsync following the README's instructions. I've checked, my token is right.
When running the following line, I get a TypeError:

**Code**
```
asyncio.run(bard.get_answer("What is Metaverse?"))
```
**Error message**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/akos326/.local/lib/python3.10/site-packages/bardapi/core_async.py", line 82, in get_answer
    self.SNlM0e = await self.SNlM0e
  File "/home/akos326/.local/lib/python3.10/site-packages/bardapi/core_async.py", line 242, in _get_snim0e
    resp = await self.client.get(
TypeError: AsyncClient.get() got an unexpected keyword argument 'follow_redirects'
```

**Version**
OS: Ubuntu 22.04
Python: 3.10
Bard API: 0.1.29
Using proxy: no

**Comment by yihong0618** [comment]
pip install -U httpx
