### ISSUE TITLE
Token not work

### ISSUE THREAD

**Issue by SongZihan** [dsdanielpark/Bard-API#176]
After confirming that my browser runs bard well , I copied the token. But an error occurred (and also in colab):
`Traceback (most recent call last):
  File "W:\PythonDoc\ChatAPI\BardApi.py", line 4, in <module>
    bard = Bard(token=token)
  File "W:\cache\ChatAPI\lib\site-packages\bardapi\core.py", line 55, in __init__
    self.SNlM0e = self._get_snim0e()
  File "W:\cache\ChatAPI\lib\site-packages\bardapi\core.py", line 129, in _get_snim0e
    raise Exception(
Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.`

And I check the code in core.py, I find that :
`        if resp.status_code != 200:
            raise Exception(
                f"Response status code is not 200. Response Status is {resp.status_code}"
            )
        print(resp.text)
       snim0e = re.search(r"SNlM0e\":\"(.*?)\"", resp.text)
        if not snim0e:
            raise Exception(
                "SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'."
            )
`
The resp seems works. But `snim0e = re.search(r"SNlM0e\":\"(.*?)\"", resp.text)` The regex doesn't seem to match.
I'm guessing maybe Google changed the structure of the page or something.

Please see if you can fix it. Thanks.

**Comment by SongZihan** [comment]
Sorry for write same issue with: https://github.com/dsdanielpark/Bard-API/issues/155
