### ISSUE TITLE
Bard api error when importing the api

### ISSUE THREAD

**Issue by admin-relu** [dsdanielpark/Bard-API#198]
`
from bardapi import Bard
from dotenv import load_dotenv
import os 

load_dotenv()

token = os.getenv("BARD_API_KEY")

bard = Bard(token= token)

result = bard.get_answer("what is the crrent weather in cancun")

print(result)
`

***
python3 bard.py
Traceback (most recent call last):
  File "/Users/user/test-bard/bard.py", line 1, in <module>
    from bardapi import Bard
  File "/Users/user/.pyenv/versions/3.11.3/lib/python3.11/site-packages/bardapi/__init__.py", line 4, in <module>
    from bardapi.core import Bard
  File "/Users/user/.pyenv/versions/3.11.3/lib/python3.11/site-packages/bardapi/core.py", line 28, in <module>
    from bardapi.models.result import BardResult
  File "/Users/user/.pyenv/versions/3.11.3/lib/python3.11/site-packages/bardapi/models/result.py", line 3, in <module>
    from bardapi.models.draft import BardDraft
  File "/Users/user/.pyenv/versions/3.11.3/lib/python3.11/site-packages/bardapi/models/draft.py", line 9, in <module>
    from bardapi.models.tools.map import BardMapContent
  File "/Users/user/.pyenv/versions/3.11.3/lib/python3.11/site-packages/bardapi/models/tools/map.py", line 6, in <module>
    class BardMapsPoint:
  File "/Users/user/.pyenv/versions/3.11.3/lib/python3.11/site-packages/bardapi/models/tools/map.py", line 58, in BardMapsPoint
    def title(self) -> Tuple[str, str]:
                       ^^^^^
NameError: name 'Tuple' is not defined. Did you mean: 'tuple'?

***

**Comment by dsdanielpark** [comment]
During the optimization and refactoring process, I identified formatting and import errors. These issues have been addressed through QA to prevent recurrence.

Please use `0.1.33` or `0.1.37` version.
