### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ArchisaBiswas** [dsdanielpark/Bard-API#199]
The Error Traceback is:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\Mood_Player_Try5\Back-End\venv\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\admin\Desktop\Mood_Player_Try5\Back-End\venv\lib\site-packages\flask\app.py", line 2193, in wsgi_app       
    response = self.handle_exception(e)
  File "C:\Users\admin\Desktop\Mood_Player_Try5\Back-End\venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\Desktop\Mood_Player_Try5\Back-End\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app       
    response = self.full_dispatch_request()
  File "C:\Users\admin\Desktop\Mood_Player_Try5\Back-End\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\Desktop\Mood_Player_Try5\Back-End\venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\Desktop\Mood_Player_Try5\Back-End\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\Desktop\Mood_Player_Try5\Back-End\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\Desktop\Mood_Player_Try5\Back-End\app.py", line 20, in query_bard
    result = bard.get_answer(query)
  File "C:\Users\admin\Desktop\Mood_Player_Try5\Back-End\venv\lib\site-packages\bardapi\core.py", line 272, in get_answer   
    "content": parsed_answer[4][0][1][0],
TypeError: 'NoneType' object is not subscriptable

This is the error I get when the code with the line: result = bard.get_answer(query) is run. I have even tried to clear the cookies, re-start the browser, and then replace with the new Cookie value and run it and sometimes it returns the response but other and most times, it replies with the above error, i.e. it is returning None.

Below is the version of the bardapi that I am using:

![image](https://github.com/dsdanielpark/Bard-API/assets/86257647/a6a4fe89-1855-4464-9ca4-22b9bda67d7e)

Thank you so much for making this API. Much appreciated for any help in advance. Thank you!

**Comment by dsdanielpark** [comment]
During the optimization and refactoring process, I identified formatting and import errors. These issues have been addressed through QA to prevent recurrence.

Please use `0.1.33` or `0.1.37` version.
