### ISSUE TITLE
json.decoder.JSONDecodeError Not able to get response from bard

### ISSUE THREAD

**Issue by bhavik-malhotra** [dsdanielpark/Bard-API#224]
Hey, so i was using my script and it was working fine, since the last 2 days it is not working properly I've tried upgrading to the latest bardapi version from 0.1.33 to 0.1.38 but still not getting the desired response from bard. I have tried resetting my cookies, changed my network as well.
OS: Windows 11
Python: 3.11
Using proxy: No

Bardapi==0.1.38 Error Message
**Error**
```
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Scripts\main.py", line 302, in <module>
    main()
  File "C:\Users\Admin\Documents\Scripts\main.py", line 257, in main
    bard_report_name = bard_report(reference)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Scripts\main.py", line 70, in bard_report
    final_response = bard.get_answer(prompt)['content']
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bardapi\core.py", line 332, in get_answer
    resp_dict = json.loads(resp.content.splitlines()[-5])[0][2]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by wmcaeddy** [comment]
I have experienced some similar issues recently. 
Resetting cookie will allow the system working for a short while.

**Comment by khoi1908vn** [comment]
```py
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/app/main.py", line 669, in askbard
    bard_answer = await bard.get_answer(question)
  File "/opt/venv/lib/python3.10/site-packages/bardapi/core_async.py", line 225, in get_answer
    resp_dict = json.loads(resp.content.splitlines()[3])[0][2]
IndexError: list index out of range
```
I got a similar exception to this one; I think Google changed how Bard behaves.

**Comment by dsdanielpark** [comment]
Google Bard doesn't seem to have changed its interface; it appears to be an issue that has been present since its inception. The responses could be due to a temporary ban, rate limiting, or failure to receive well-structured answers to repeated identical questions.

However, this was temporary, and it was observed that normal functionality resumed after some time.
These issues could manifest as index errors or encoding errors.


### Possible error messages
- Numerous users reported the issue as a temporary glitch resolved by resetting cookies, restarting the browser, logging in, or waiting it out. (Mostly resolved over time).

```python
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/app/main.py", line 669, in askbard
    bard_answer = await bard.get_answer(question)
  File "/opt/venv/lib/python3.10/site-packages/bardapi/core_async.py", line 225, in get_answer
    resp_dict = json.loads(resp.content.splitlines()[3])[0][2]
IndexError: list index out of range
```

or 
```python
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Scripts\main.py", line 302, in <module>
    main()
  File "C:\Users\Admin\Documents\Scripts\main.py", line 257, in main
    bard_report_name = bard_report(reference)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Scripts\main.py", line 70, in bard_report
    final_response = bard.get_answer(prompt)['content']
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bardapi\core.py", line 332, in get_answer
    resp_dict = json.loads(resp.content.splitlines()[-5])[0][2]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by khoi1908vn** [comment]
Thanks for your help. I tried with new cookies and it worked.
