### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by marco99asr** [dsdanielpark/Bard-API#225]
root@macco:/home/ubuntu/be# /usr/bin/python3 /home/ubuntu/be/flask_be.py
Traceback (most recent call last):
  File "/home/ubuntu/be/flask_be.py", line 8, in <module>
    from bardapi import Bard
  File "/usr/local/lib/python3.8/dist-packages/bardapi/__init__.py", line 4, in <module>
    from bardapi.core import Bard
  File "/usr/local/lib/python3.8/dist-packages/bardapi/core.py", line 28, in <module>
    from bardapi.models.result import BardResult
  File "/usr/local/lib/python3.8/dist-packages/bardapi/models/result.py", line 3, in <module>
    from bardapi.models.draft import BardDraft
  File "/usr/local/lib/python3.8/dist-packages/bardapi/models/draft.py", line 5, in <module>
    from bardapi.models.tools.flight import BardFlightContent
  File "/usr/local/lib/python3.8/dist-packages/bardapi/models/tools/flight.py", line 4, in <module>
    class BardFlight:
  File "/usr/local/lib/python3.8/dist-packages/bardapi/models/tools/flight.py", line 17, in BardFlight
    def airlines(self) -> list[str]:
TypeError: 'type' object is not subscriptable
root@macco:/home/ubuntu/be#

**Comment by dsdanielpark** [comment]
Solution: Reinstall with the GitHub dev version or use Python version 3.9 or higher.

Are you using the GitHub dev version or the PyPI version 0.1.38? It seems like you might be using the GitHub dev version. If that's the case, since Python officially supports typing starting from version 3.9, please upgrade your Python version to 3.9 or higher, or update to the current GitHub dev version. (For the current GitHub dev version of bardapi, there is no issue with type hints even on Python versions 3.8 and below because we have imported a separate module to handle it.)

**Comment by marco99asr** [comment]
root@macco:/home/ubuntu/be# python3 --version
Python 3.8.10
root@macco:/home/ubuntu/be# pip3 list | grep -ie bard
/usr/bin/pip3:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
bardapi                  0.1.38

**Comment by marco99asr** [comment]
Ok now with py3.9 works
root@macco:/home/ubuntu/be# python3.9 -m pip install git+https://github.com/dsdanielpark/Bard-API.git         ^C
root@macco:/home/ubuntu/be# /usr/bin/python3.9 /home/ubuntu/be/flask_be.py
2023-11-06 21:06:25,449 - DEBUG - Starting __main__ ....



but i receive this error

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ubuntu/be/flask_be.py", line 444, in search
    return search_json(location, radius)
  File "/home/ubuntu/be/flask_be.py", line 296, in search_json
    return getMushrums(forests)
  File "/home/ubuntu/be/flask_be.py", line 267, in getMushrums
    bard = Bard(token=token)
  File "/usr/local/lib/python3.9/dist-packages/bardapi/core.py", line 79, in __init__
    self.SNlM0e = self._get_snim0e()
  File "/usr/local/lib/python3.9/dist-packages/bardapi/core.py", line 155, in _get_snim0e
    raise Exception(
Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.
