### ISSUE TITLE
TypeError: Too many arguments for typing.List; actual 2, expected 1

### ISSUE THREAD

**Issue by myreallycoolusername** [dsdanielpark/Bard-API#260]
I got this error while using bard-api:

```
Traceback (most recent call last):
  File "/workspace/main.py", line 9, in <module>
    from bardapi import Bard
  File "/app/.heroku/python/lib/python3.12/site-packages/bardapi/__init__.py", line 4, in <module>
    from bardapi.core import Bard
  File "/app/.heroku/python/lib/python3.12/site-packages/bardapi/core.py", line 28, in <module>
    from bardapi.models.result import BardResult
  File "/app/.heroku/python/lib/python3.12/site-packages/bardapi/models/result.py", line 31, in <module>
    class BardResult:
  File "/app/.heroku/python/lib/python3.12/site-packages/bardapi/models/result.py", line 38, in BardResult
    def search_queries(self) -> List[str, int]:
                                ~~~~^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.12/typing.py", line 384, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.12/typing.py", line 1436, in __getitem__
    _check_generic(self, params, self._nparams)
  File "/app/.heroku/python/lib/python3.12/typing.py", line 304, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
TypeError: Too many arguments for typing.List; actual 2, expected 1
```

Is there a solution?

**Comment by dsdanielpark** [comment]
#225, #228

Solution: Reinstall with the GitHub dev version or use Python version 3.9 or lower.

This is due to changes in how type hints are written. While some type hints have been made more flexible to work from Python 3.6 to Python 3.9, there have been ongoing changes to type hints in Python since version 3.10. Therefore, it's important to update your type hints. However, compatibility with versions after Python 3.10 may not be as robust yet, so it's advisable to use Python versions below 3.10.

Reference: https://docs.python.org/ko/3.11/library/typing.html, https://docs.python.org/3/library/typing.html
