### ISSUE TITLE
ChatBard: token_from_browser

### ISSUE THREAD

**Issue by johnd0e** [dsdanielpark/Bard-API#265]
**Describe the bug**
Unable to use `token_from_browser` in `ChatBard`

**Version**
Bard API: 0.1.39

**Code**
```python
from bardapi import ChatBard
chat = ChatBard(token_from_browser=True)
chat.start()
```
**Error**
```
Enter the Bard API Key(__Secure-1PSID):
Bard API(__Secure-1PSID) Key must be entered.
```
The issue is here:
https://github.com/dsdanielpark/Bard-API/blob/9345c2c12cf11346f3a1ace2a24c130331fb3de5/bardapi/chat.py#L52-L53

Instead it should be:
```py
        self.token_from_browser = token_from_browser
        self.token = None if token_from_browser else token or os.getenv("_BARD_API_KEY") or self._get_api_key()
```

**Comment by johnd0e** [comment]
Another issue is here:
https://github.com/dsdanielpark/Bard-API/blob/9345c2c12cf11346f3a1ace2a24c130331fb3de5/bardapi/core.py#L110

`cookies=False` means that only `__Secure-1PSID` is used.
But that does not work for my case, I need all 3 cookies.
And there is no way to achieve with `ChatBard`.

**Comment by dsdanielpark** [comment]
I will check this issue and see all code again. Thank you!

**Comment by dsdanielpark** [comment]
As you know, this package was initially very simple, anticipating its obsolescence with the launch of the official Bard API. 

However, as Bard expanded to offer various services, the structure became more complex, and diverse features were added in response to developers' requests. Consequently, I couldn't neatly organize all use cases within a single Bard structure, and although Async seemed of limited utility, it was updated as needed.

For Multi Cookie Bard, a new structure, BardCookies, inheriting from Bard, was placed in a new Python file.

In ChatBard, implementing multicookies in Bard via token_from_browser in core.py called for further modifications, so I've made the following changes:

https://github.com/dsdanielpark/Bard-API/blob/main/bardapi/chat.py#L209

ChatBard has been modified to inherit from BardCookies, which in turn has been adjusted to fetch three cookie values via token_from_browser.

After reinstalling from the GitHub version (after a clean uninstallation), please try it out and let us know if any errors occur. As I only need a single cookie, I couldn't debug this directly.

Thank you for reporting the error.

```
$ pip install git+https://github.com/dsdanielpark/Bard-API.git
```


```python
from bardapi import ChatBardCookies
chat = ChatBardCookies(token_from_browser=True)
chat.start()
```

**Comment by johnd0e** [comment]
```py
from bardapi import ChatBard
chat = ChatBard(token_from_browser=True)
chat.start()
```
```
Traceback (most recent call last):
  File "D:\AI\Bard-API\main1.py", line 1, in <module>
    from bardapi import ChatBard
  File "D:\AI\Bard-API\bardapi\__init__.py", line 5, in <module>
    from bardapi.chat import ChatBard, ChatBardCookise
  File "D:\AI\Bard-API\bardapi\chat.py", line 7, in <module>
    from bardapi import BardCookies
ImportError: cannot import name 'BardCookies' from partially initialized module 'bardapi' (most likely due to a circular import) (D:\AI\Bard-API\bardapi\__init__.py)
```
Note `Cookise`. Perhaps there are some mistypes left.

**Comment by dsdanielpark** [comment]
I am currently working on implementing multi-cookies to the Bard object due to the issue with multiple inheritance. 

Additionally, I will also be conducting some overall code refactoring. This change will be updated in version 0.1.40 and documented to accommodate the inclusion of multi-cookies within the Bard object.

**Comment by dsdanielpark** [comment]
I have just finished but QA process will be needed.

**Comment by johnd0e** [comment]
In https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_DEV.md#multi-cookie-bard described 3 ways, but there are some errors/mistypes in description.

So here what I have exactly tried:
(only 1 case is successful)

## BardCookies + cookie_dict
```
from bardapi import BardCookies

cookie_dict = {
    # Any cookie values you want to pass session object.
}

bard = BardCookies(cookie_dict=cookie_dict)
print(bard.get_answer("こんにちは")['content'])
```

This works!

## BardCookies + session
```
import requests
from bardapi import BardCookies, SESSION_HEADERS

session = requests.Session()
#session.cookies.set("__Secure-1PSID", 
#...
session.headers = SESSION_HEADERS

bard = BardCookies(session=session)
bard.get_answer("How is the weather today in seoul?")
```
```
The BardCookies class is no longer in use.
Please use the Bard class with the 'cookie_dict' and 'multi_cookies_bool' arguments in the Bard constructor.
Traceback (most recent call last):
  File "D:\AI\Bard-API\main02.py", line 11, in <module>
    bard = BardCookies(session=session)
  File "D:\AI\Bard-API\bardapi\core_cookies.py", line 50, in __init__
    self.cookie_dict = cookie_dict or self._get_token(token_from_browser)
  File "D:\AI\Bard-API\bardapi\core_cookies.py", line 81, in _get_token
    raise Exception(
Exception: Bard API Key must be provided as token argument or extracted from browser.
```

## Bard + session
```
import requests
from bardapi import Bard, SESSION_HEADERS

session = requests.Session()
#session.cookies.set("__Secure-1PSID", 
#...
session.headers = SESSION_HEADERS

bard = Bard(session=session)
bard.get_answer("How is the weather today in seoul?")
```
```
Traceback (most recent call last):
  File "D:\AI\Bard-API\main021.py", line 11, in <module>
    bard = Bard(session=session, multi_cookies_bool=True)
  File "D:\AI\Bard-API\bardapi\core.py", line 74, in __init__
    self.token = self._get_token(token, token_from_browser, multi_cookies_bool)
  File "D:\AI\Bard-API\bardapi\core.py", line 136, in _get_token
    raise Exception(
Exception: Bard API Key must be provided as the 'token' argument or extracted from the browser.
```

## Bard +token_from_browser + multi_cookies_bool
```
from bardapi import Bard

bard = Bard(token_from_browser=True, multi_cookies_bool=True)
bard.get_answer("How is the weather today in seoul?")
```
```
Traceback (most recent call last):
  File "D:\AI\Bard-API\main03.py", line 3, in <module>
    bard = Bard(token_from_browser=True, multi_cookies_bool=True)
  File "D:\AI\Bard-API\bardapi\core.py", line 82, in __init__
    self.SNlM0e = self._get_snim0e()
  File "D:\AI\Bard-API\bardapi\core.py", line 181, in _get_snim0e
    raise Exception(
Exception: Response status code is not 200. Response Status is 404
```

**Comment by aniruddhkrish** [comment]
Here is my code for extracting cookies from the browser but I have done only with firefox. So, install firefox and login to Gemini formerly Bard. Then run this code to get the cookies and use the API. 


```python

import requests
from bardapi import Bard, SESSION_HEADERS, BardCookies
import browser_cookie3

domain = '.google.com'

firefox_cookies = browser_cookie3.firefox(domain_name=domain)

psid = '__Secure-1PSID'
dts = '__Secure-1PSIDTS'
dcc = '__Secure-1PSIDCC'
nid = 'NID'

psid_value = None
dts_value = None
dcc_value = None
nid_value = None

for cookie in firefox_cookies:
    if cookie.name == psid:
        psid_value = cookie.value
    elif cookie.name == dts:
        dts_value = cookie.value
    elif cookie.name == dcc:
        dcc_value = cookie.value
    elif cookie.name == nid:
        nid_value = cookie.value


cookie_dict = {
    "__Secure-1PSID": psid_value,
    "__Secure-1PSIDTS": dts_value,
    "__Secure-1PSIDCC": dcc_value,
}
session = requests.Session()
session.cookies.set("__Secure-1PSID", psid_value)
session.cookies.set( "__Secure-1PSIDCC", dcc_value)
session.cookies.set("__Secure-1PSIDTS", dts_value)
session.cookies.set("NID",nid_value)
session.headers = SESSION_HEADERS

bard = BardCookies(session=session,cookie_dict=cookie_dict)
var = bard.get_answer("Hi")['content']

while True:

    question = str(input("Enter your prompt: ")).lower()
    response = bard.get_answer(question)['content']
    data = str(response).replace("*", "")
    print(data) 
'''
Notice : Google has rebranded Bard as Gemini. So it will affect the API. I have created an issue and you may visit it. Solutions have been provided there.

**Comment by aniruddhkrish** [comment]
I used this code after updating the core.py, core.cookies, constant.py, for the new Gemini formerly Bard.  Refer to the issue created by me "Google renames its chatbot Bard to Gemini"

I have provided the solution here using browser_cookie3. I have only tested for firefox. So you may install firefox, and sign in Gemini through your google account credentials, and run this code. 
```python
from bardapi import SESSION_HEADERS, BardCookies
import browser_cookie3
import requests
domain = '.google.com'

firefox_cookies = browser_cookie3.firefox(domain_name=domain)

psid = '__Secure-1PSID'
dts = '__Secure-1PSIDTS'
dcc = '__Secure-1PSIDCC'
nid = 'NID'

psid_value = None
dts_value = None
dcc_value = None
nid_value = None

for cookie in firefox_cookies:
    if cookie.name == psid:
        psid_value = cookie.value
    elif cookie.name == dts:
        dts_value = cookie.value
    elif cookie.name == dcc:
        dcc_value = cookie.value
    elif cookie.name == nid:
        nid_value = cookie.value


cookie_dict = {
    "__Secure-1PSID": psid_value,
    "__Secure-1PSIDTS": dts_value,
    "__Secure-1PSIDCC": dcc_value,
}
session = requests.Session()
session.cookies.set("__Secure-1PSID", psid_value)
session.cookies.set( "__Secure-1PSIDCC", dcc_value)
session.cookies.set("__Secure-1PSIDTS", dts_value)
session.cookies.set("NID",nid_value)
session.headers = SESSION_HEADERS

bard = BardCookies(session=session,cookie_dict=cookie_dict)

while True:

    question = input("Enter your prompt to Gemini: ")
    response = bard.get_answer(question)['content']
    data = str(response).replace("*", "")
    print(data)

```

**Comment by dsdanielpark** [comment]
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API
