### ISSUE TITLE
ImportError: cannot import name 'BardCookies' from partially initialized module 'bardapi' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by myreallycoolusername** [dsdanielpark/Bard-API#266]
I have an error using the package:
```
Traceback (most recent call last):
  File "/workspace/main.py", line 22, in <module>
    from bardapi import Bard
  File "/app/.heroku/python/lib/python3.12/site-packages/bardapi/__init__.py", line 5, in <module>
    from bardapi.chat import ChatBard, ChatBardCookise
  File "/app/.heroku/python/lib/python3.12/site-packages/bardapi/chat.py", line 7, in <module>
    from bardapi import BardCookies
ImportError: cannot import name 'BardCookies' from partially initialized module 'bardapi' (most likely due to a circular import) (/app/.heroku/python/lib/python3.12/site-packages/bardapi/__init__.py)
```

**Comment by dsdanielpark** [comment]
I will check and, if necessary, apply a hotfix for a quick release of version 0.1.40.

Are you by any chance using version bardapi==`0.1.39`?

Please check by using:

```python
import bardapi

print(bardapi.__version__)
```

I would appreciate it.

---

**Comment by F33RNI** [comment]
Same

```python
╰─ python           
Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bardapi import Bard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/lib/python3.11/site-packages/bardapi/__init__.py", line 5, in <module>
    from bardapi.chat import ChatBard, ChatBardCookise
  File ".../venv/lib/python3.11/site-packages/bardapi/chat.py", line 7, in <module>
    from bardapi import BardCookies
ImportError: cannot import name 'BardCookies' from partially initialized module 'bardapi' (most likely due to a circular import) (.../venv/lib/python3.11/site-packages/bardapi/__init__.py)
>>> import bardapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/lib/python3.11/site-packages/bardapi/__init__.py", line 5, in <module>
    from bardapi.chat import ChatBard, ChatBardCookise
  File ".../venv/lib/python3.11/site-packages/bardapi/chat.py", line 7, in <module>
    from bardapi import BardCookies
ImportError: cannot import name 'BardCookies' from partially initialized module 'bardapi' (most likely due to a circular import) (.../venv/lib/python3.11/site-packages/bardapi/__init__.py)
>>> 

```

**Comment by myreallycoolusername** [comment]
Confirmed that I'm using the latest version (0.1.39)

**Comment by dsdanielpark** [comment]
[myreallycoolusername](https://github.com/myreallycoolusername)

Thank you. I will double-check and update the GitHub version installation. I appreciate your valuable issue report.

**Comment by dsdanielpark** [comment]
#267 #265 

The GitHub version is currently being worked on, so this issue is temporary and has been resolved for now. Thank you for reporting the issue.
