### ISSUE TITLE
Not able to get response

### ISSUE THREAD

**Issue by prashantsmp** [dsdanielpark/Bard-API#27]
I have followed the procedures in the **Read.me** file.

```
from bardapi import Bard
import os
os.environ['_BARD_API_KEY']='WwXXXXXjQIGRj3Cno871zb4FRW1smDrQH10e1H7GbD5LeU9m02OlZJj5-XX.'

# response = Bard().get_answer("나와 내 동년배들이 좋아하는 뉴진스에 대해서 알려줘")['content']
response = Bard().get_answer("What is Bard API")['content']
print(response)
```

First i have tried with example snippets, i got the below error.

> Traceback (most recent call last):
>   File "PyCharmProjects/Bard-API/scripts/google_bard_api.py", line 13, in <module>
>     response = Bard().get_answer("나와 내 동년배들이 좋아하는 뉴진스에 대해서 알려줘")['content']
>   File "PyCharmProjects/Bard-API/bardapi/core.py", line 130, in get_answer
>     translator_to_lang = GoogleTranslator(source="auto", target=self.language)
>   File "PyCharmProjects/Bard-API/venv/lib/python3.10/site-packages/deep_translator/google.py", line 39, in __init__
>     super().__init__(
>   File "PyCharmProjects/Bard-API/venv/lib/python3.10/site-packages/deep_translator/base.py", line 42, in __init__
>     raise InvalidSourceOrTargetLanguage(target)
> deep_translator.exceptions.InvalidSourceOrTargetLanguage: None --> Invalid source or target language!

then i have changed the input text to english language, and again i got the same error.

> Traceback (most recent call last):
>   File "PyCharmProjects/Bard-API/scripts/google_bard_api.py", line 14, in <module>
>     response = Bard().get_answer("What is Bard API")['content']
>   File "PyCharmProjects/Bard-API/bardapi/core.py", line 130, in get_answer
>     translator_to_lang = GoogleTranslator(source="auto", target=self.language)
>   File "PyCharmProjects/Bard-API/venv/lib/python3.10/site-packages/deep_translator/google.py", line 39, in __init__
>     super().__init__(
>   File "PyCharmProjects/Bard-API/venv/lib/python3.10/site-packages/deep_translator/base.py", line 42, in __init__
>     raise InvalidSourceOrTargetLanguage(target)
> deep_translator.exceptions.InvalidSourceOrTargetLanguage: None --> Invalid source or target language!

Could anybody get help me here?

**Comment by dsdanielpark** [comment]
If you have downloaded the version that supports multiple languages through GitHub, please set the following argument:


os.environ["_BARD_API_LANG"] = 'en'


Also, reset the environment variables and try again.
