### ISSUE TITLE
After update I get 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by phamxtien** [dsdanielpark/Bard-API#40]

**Comment by dsdanielpark** [comment]
Please give me a code and version about error.

**Comment by andreabac3** [comment]
Hi,
I have the same issue.
I am following this guide:
```python3
from bardapi import Bard
token = '< REPLACE WITH MY TOKEN >'
bard = Bard(token=token)
bard.get_answer("나와 내 동년배들이 좋아하는 뉴진스에 대해서 알려줘")['content']
```

Error:
```python3
>>> bard.get_answer("나와 내 동년배들이 좋아하는 뉴진스에 대해서 알려줘")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/bardapi/core.py", line 148, in get_answer
    for img in resp_json[4][0][4]:
TypeError: 'NoneType' object is not iterable
```

Thank you for the attention!

**Comment by phamxtien** [comment]
```
def bardChat(prompt):
    import bardapi
    cookies = readCookieFile('bard')
    BARD_TOKEN = ''
    for item in cookies:
        if item['name'] == '__Secure-1PSID':
            BARD_TOKEN = item['value']
    
    if BARD_TOKEN == '': 
        return {'RESULT': False, 'MESSAGE': 'Bard Chat token is not found!'}
    
    print('INFO:     Bard Chat')
    try:
        response = bardapi.core.Bard(token=BARD_TOKEN).get_answer(prompt)
        text = response['content']
        text = re.sub(r'(?<![0-9]):(?![0-9])', ': ', text)
        links = ''
        if len(response['links']) > 0: links = '\nLinks:' + '\n'.join(response['links'])
        ids = f'{response["conversation_id"]} {response["response_id"]} {response["choices"][0]["id"]}'

        return {'RESULT': True, 'DATA': f'{text}{links}'}
    except Exception as e:
        return {'RESULT': True, 'DATA': f'Bard Chat: Sorry! I got an error!\n{str(e)}'}
```

**Comment by phamxtien** [comment]
I use
__version__ = "0.1.11"

**Comment by sswam** [comment]
I'm also having this problem from today.

**Comment by dsdanielpark** [comment]
It was caused by accepting a pull request without a proper review for an incomplete refactoring. Reverted, so it works fine now.

thank you

Taking this opportunity, we will once again change the policy to strictly accept pull requests.

**Comment by dsdanielpark** [comment]
All the modifications have been completed. Once you install the GitHub version again, you will be able to use version 0.1.14.

```
pip install git+https://github.com/dsdanielpark/Bard-API.git
```
