### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by megalosVigneswaran** [dsdanielpark/Bard-API#42]
Traceback (most recent call last):
  File "f:\Python_files\main.py", line 8, in <module>
    print(Bard().get_answer(input_text)['content'])
  File "F:\facereg\NEW\lib\site-packages\bardapi\core.py", line 43, in __init__
    self.SNlM0e = self._get_snim0e()
  File "F:\facereg\NEW\lib\site-packages\bardapi\core.py", line 59, in _get_snim0e
    raise Exception(
Exception: SNlM0e value not found in response. Check __Secure-1PSID value.

But i used correct id

**Comment by dsdanielpark** [comment]
The Chatbot class is not designed to accept a token (API) as argument. However, it was under consideration, so I will make the necessary modifications and update it shortly.

**Comment by megalosVigneswaran** [comment]
i used with other google account  __Secure-1PSID value it worked finely.
