### ISSUE TITLE
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by andreabac3** [dsdanielpark/Bard-API#77]
Hi,
First of all, thank you for your work @dsdanielpark .

Currently I can no longer use the library (version 0.1.11) as I get the following error:
`Traceback (most recent call last):
<PATH>/python_file.py
    bard = BardInterface()
<PATH>/python_file.py
    self.api = Bard(<MY KEY>, timeout=200)
  File "/opt/homebrew/lib/python3.10/site-packages/bardapi/core.py", line 49, in __init__
    self.SNlM0e = self._get_snim0e()
  File "/opt/homebrew/lib/python3.10/site-packages/bardapi/core.py", line 56, in _get_snim0e
    resp = self.session.get(
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
`
Can you help me?

Kind regards,
Andrea

**Comment by dsdanielpark** [comment]
Hello. The key points of the error are as follows:

```bash
TooManyRedirects: Exceeded 30 redirects. 
```


Unlike the early stages, the internal interface of Google has been changed, causing restrictions on excessive calls or the use of proxy servers, which leads to temporary blocking.

Furthermore, it has been observed that if a request is deemed abnormal (too fast), the cookie value is frequently changed.

Originally, the purpose of the bardapi package is limited testing of certain functionalities prior to the official bard API. Therefore, I recommend against misuse or abuse.

The cookie value is tied to the Google account, and you should always carefully review Google's policies.
